import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { existsSync, mkdirSync } from 'node:fs';
import { chromium } from 'playwright';
import { databaseEnvironment, readEmailCode } from './helpers.js';
import { checkCatalogue } from './catalog-browser-checks.js';

test('public catalogue, route tourism, Google Maps and real OTP challenge flow in desktop/mobile browser', {timeout:180000}, async t => {
 const env = { ...databaseEnvironment('public-browser'), PORT:'4189' };
 const child = spawn(process.execPath,['--import','./tests/email-provider.fixture.js','server.js'],{env,windowsHide:true,stdio:['ignore','pipe','pipe']});
 let browser;
 t.after(async () => { await browser?.close(); child.kill(); });
 await new Promise((resolve,reject) => { const timer = setTimeout(() => reject(new Error('Server start timeout')),20000); child.stdout.on('data',data => { if(String(data).includes('Live Train v2 running')) {clearTimeout(timer);resolve();} }); child.once('exit',code => {clearTimeout(timer);reject(new Error(`Server exit ${code}`));}); });
 const executablePath = process.env.BROWSER_PATH || ['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(existsSync);
 browser = await chromium.launch({headless:true,...(executablePath && {executablePath})});
 const page = await browser.newPage({viewport:{width:1440,height:1000}}); page.setDefaultTimeout(20000);
 const errors = []; page.on('pageerror',e => errors.push(e.message));
 await page.goto('http://127.0.0.1:4189/',{waitUntil:'domcontentloaded'});
 await checkCatalogue(page);
 await page.locator('#profileBtn').click();
 await page.waitForFunction(() => !document.querySelector('#authSubmit').disabled);
 const email = 'browser-otp@example.test';
 await page.locator('#authEmail').fill(email); await page.locator('#authSubmit').click();
 await page.waitForSelector('#authEmailCode');
 assert.ok(await page.locator('#authResend').isDisabled()); assert.match(await page.locator('#authExpiry').innerText(),/Code expires in/);
 await page.locator('#authEmailCode').fill('000000'); await page.locator('#authSubmit').click();
 await page.waitForFunction(() => document.querySelector('#authError').textContent.includes('Invalid or expired'));
 await page.locator('#authEmailCode').fill(readEmailCode(env.MAIL_TEST_OUTBOX,email));
 await page.locator('#authSubmit').click();
 await page.waitForFunction(email => document.querySelector('#profileBtn b').textContent === email,email);
 await page.reload({waitUntil:'domcontentloaded'});
 await page.waitForFunction(email => document.querySelector('#profileBtn b').textContent === email,email);
 const live = await page.request.get('http://127.0.0.1:4189/api/trains/12639/live'); assert.equal(live.status(),503);
 const booking = await page.request.post('http://127.0.0.1:4189/api/bookings',{data:{trainNumber:'12639'}}); assert.equal(booking.status(),503);
 assert.equal((await page.request.get('http://127.0.0.1:4189/api/trains/catalog')).ok(),true);
 await page.waitForSelector('.spot-card');
 mkdirSync('test-results',{recursive:true}); await page.screenshot({path:'test-results/public-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844}); await page.screenshot({path:'test-results/public-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);
});
