import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import { chromium } from 'playwright';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import '../scripts/stage-pages.js';
import { checkCatalogue } from './catalog-browser-checks.js';
test('public catalogue and route tourism work on GitHub Pages under a repository path', {timeout:90000}, async t => {
 const app = express(); app.use('/live-train-',express.static(fileURLToPath(new URL('../dist/pages/',import.meta.url))));
 const server = app.listen(0,'127.0.0.1'); await new Promise(resolve => server.once('listening',resolve));
 let browser;
 t.after(async () => { await browser?.close(); await new Promise(resolve => server.close(resolve)); });
 const executablePath = process.env.BROWSER_PATH || ['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(existsSync);
 browser = await chromium.launch({headless:true,...(executablePath && {executablePath})});
 const page = await browser.newPage({viewport:{width:1440,height:1000}}); page.setDefaultTimeout(20000);
 const origin = `http://127.0.0.1:${server.address().port}`, errors = [], failed = [];
 page.on('pageerror',e => errors.push(e.message)); page.on('response',r => {if(r.url().startsWith(origin) && r.status() >= 400) failed.push(r.url());});
 await page.goto(origin+'/live-train-/',{waitUntil:'domcontentloaded'});
 await checkCatalogue(page);
 await page.locator('#profileBtn').click(); assert.ok(await page.locator('#authSubmit').isDisabled());
 assert.match(await page.locator('#authError').innerText(),/No code has been sent/);
 assert.deepEqual(errors,[]); assert.deepEqual(failed,[]);
});
