import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const root = new URL('../', import.meta.url);
const source = (await readFile(new URL('public/index.html', root), 'utf8')).replace(/\r\n/g, '\n');
const entry = source.replace('<html lang="en">', '<html lang="en" data-hosting="static">').replace('<head>', '<head>\n  <!-- Generated by npm run build:pages. Edit public/index.html. -->\n  <base href="./public/">');
const path = new URL('index.html', root);
if (process.argv.includes('--check')) {
  const current = (await readFile(path, 'utf8').catch(() => '')).replace(/\r\n/g, '\n');
  if (current !== entry) throw new Error('Pages entry is outdated. Run npm run build:pages and commit index.html.');
  console.log('GitHub Pages entry is up to date.');
} else {
  await writeFile(path, entry);
  await writeFile(new URL('.nojekyll', root), '');
  console.log(`GitHub Pages entry generated: ${fileURLToPath(path)}`);
}
